backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "certificates"
    label: "Certificates"
    folder: "content/certificates"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true, pattern: ['^.{1,600}$', "Max 100 words (600 characters)"]}
      - {label: "Certificate File", name: "file", widget: "file", required: true, media_folder: "/uploads/certificates"}
      - {label: "Caption", name: "caption", widget: "markdown", required: false, pattern: ['^.{0,12000}$', "Max 2000 words (12000 characters)"]}
      - {label: "Order", name: "order", widget: "number", default: 0, value_type: "int"}

  - name: "portfolio-prompt-engineering"
    label: "Portfolio → Prompt Engineering"
    folder: "content/portfolio/prompt-engineering"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true, pattern: ['^.{1,600}$', "Max 100 words"]}
      - {label: "File", name: "file", widget: "file", required: true, media_folder: "/uploads/portfolio/prompt-engineering"}
      - {label: "Caption", name: "caption", widget: "markdown", required: false, pattern: ['^.{0,12000}$', "Max 2000 words"]}
      - {label: "Order", name: "order", widget: "number", default: 0, value_type: "int"}

  - name: "portfolio-content-writing"
    label: "Portfolio → Content Writing"
    folder: "content/portfolio/content-writing"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true, pattern: ['^.{1,600}$', "Max 100 words"]}
      - {label: "File", name: "file", widget: "file", required: true, media_folder: "/uploads/portfolio/content-writing"}
      - {label: "Caption", name: "caption", widget: "markdown", required: false, pattern: ['^.{0,12000}$', "Max 2000 words"]}
      - {label: "Order", name: "order", widget: "number", default: 0, value_type: "int"}

  - name: "portfolio-image-generation"
    label: "Portfolio → Image Generation"
    folder: "content/portfolio/image-generation"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true, pattern: ['^.{1,600}$', "Max 100 words"]}
      - {label: "File", name: "file", widget: "file", required: true, media_folder: "/uploads/portfolio/image-generation"}
      - {label: "Caption", name: "caption", widget: "markdown", required: false, pattern: ['^.{0,12000}$', "Max 2000 words"]}
      - {label: "Order", name: "order", widget: "number", default: 0, value_type: "int"}

  - name: "portfolio-video-generation"
    label: "Portfolio → Video Generation"
    folder: "content/portfolio/video-generation"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true, pattern: ['^.{1,600}$', "Max 100 words"]}
      - {label: "File", name: "file", widget: "file", required: true, media_folder: "/uploads/portfolio/video-generation"}
      - {label: "Caption", name: "caption", widget: "markdown", required: false, pattern: ['^.{0,12000}$', "Max 2000 words"]}
      - {label: "Order", name: "order", widget: "number", default: 0, value_type: "int"}

  - name: "portfolio-ai-automations"
    label: "Portfolio → AI Automations"
    folder: "content/portfolio/ai-automations"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true, pattern: ['^.{1,600}$', "Max 100 words"]}
      - {label: "File", name: "file", widget: "file", required: true, media_folder: "/uploads/portfolio/ai-automations"}
      - {label: "Caption", name: "caption", widget: "markdown", required: false, pattern: ['^.{0,12000}$', "Max 2000 words"]}
      - {label: "Order", name: "order", widget: "number", default: 0, value_type: "int"}
